name = "flow-ops"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[secrets_store_secrets]]
binding = "FWP_GEMINI_API_KEY"
store_id = "8602c0b6a1d94696971a2aedf8afdfd9"
secret_name = "FWP_GEMINI_API_KEY"

[[secrets_store_secrets]]
binding = "FWP_OPENAI_API_KEY"
store_id = "8602c0b6a1d94696971a2aedf8afdfd9"
secret_name = "FWP_OPENAI_API_KEY"
